name: "Terraform"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  bootstrap:
    name: "Terraform Bootstrap"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/bootstrap
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::157583859662:role/tf-dev-mum-iam-assume-role
          aws-region: ap-south-1
          role-session-name: GithubActionsSession

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format
        run: terraform fmt -recursive  # Changed from fmt -check to fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  dev-environment:
    name: "Terraform Dev Environment"
    needs: bootstrap
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::157583859662:role/tf-dev-mum-iam-assume-role
          aws-region: ap-south-1
          role-session-name: GithubActionsSession

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format
        run: terraform fmt -recursive  # Changed from fmt -check to fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan